// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUYsM23MrDoQ2N4XZyqw6OXxjMvrds6xE',
    appId: '1:1050043362542:web:a2abf3bdda9a88fff157ff',
    messagingSenderId: '1050043362542',
    projectId: 'shop-app-b6f9b',
    authDomain: 'shop-app-b6f9b.firebaseapp.com',
    storageBucket: 'shop-app-b6f9b.firebasestorage.app',
    measurementId: 'G-W8PFPNQM2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCihoza5b4OV8URQwHWxoWvlhDbpkwGFe4',
    appId: '1:1050043362542:android:20c0453e45bd4c9ff157ff',
    messagingSenderId: '1050043362542',
    projectId: 'shop-app-b6f9b',
    storageBucket: 'shop-app-b6f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsOjbwimjqlNWzXCU4aasQ0pm9V4UeEgE',
    appId: '1:1050043362542:ios:4cca1fddbb919b70f157ff',
    messagingSenderId: '1050043362542',
    projectId: 'shop-app-b6f9b',
    storageBucket: 'shop-app-b6f9b.firebasestorage.app',
    iosBundleId: 'com.example.myApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsOjbwimjqlNWzXCU4aasQ0pm9V4UeEgE',
    appId: '1:1050043362542:ios:4cca1fddbb919b70f157ff',
    messagingSenderId: '1050043362542',
    projectId: 'shop-app-b6f9b',
    storageBucket: 'shop-app-b6f9b.firebasestorage.app',
    iosBundleId: 'com.example.myApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUYsM23MrDoQ2N4XZyqw6OXxjMvrds6xE',
    appId: '1:1050043362542:web:a53739706b3f3805f157ff',
    messagingSenderId: '1050043362542',
    projectId: 'shop-app-b6f9b',
    authDomain: 'shop-app-b6f9b.firebaseapp.com',
    storageBucket: 'shop-app-b6f9b.firebasestorage.app',
    measurementId: 'G-T7SWLW9WRZ',
  );
}
